name = "stdin"
version = "1.0.0"
description = "`stdin` provides a synchronous iterator for consuming stdin. It supports all the non-browser targets, Erlang, Node, Deno, and Bun."
licences = ["MIT"]
repository = { type = "github", user = "olian04", repo = "gleam-stdin" }

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"

[javascript]
typescript_declarations = true
